name: XML validation
description: "Validate JATS/Crossref XML files"
inputs:
  jats_path:
    description: The path to the JATS file to be validated
    required: false
  crossref_path:
    description: The path to the Crossref XML file to be validated
    required: false
  validation_mode:
    description: "Validation mode: draft (will allow invalid DOI values) or strict"
    required: false
    default: draft
runs:
  using: "composite"
  steps:
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.1
        bundler-cache: true
        cache-version: validate-xml-files
        bundler: Gemfile.lock
        working-directory: ${{ github.action_path }}
    - name: Validate files
      id: validator
      shell: bash
      env:
        JATS_PATH: ${{ inputs.jats_path }}
        CROSSREF_PATH: ${{ inputs.crossref_path }}
        VALIDATION_MODE: ${{ inputs.validation_mode }}
        BUNDLE_GEMFILE: ${{ github.action_path }}/Gemfile
      run: |
        bundle exec ruby ${{ github.action_path }}/validate_files.rb
branding:
  icon: check-square
  color: green
